### ISSUE TITLE
store.versionHistory is not a function

### ISSUE THREAD

**Issue by like202012** [facundoolano/app-store-scraper#223]
When I called the `versionHistory` function, I got the error "store.versionHistory is not a function". However, I've checked and found that the `versionHistory` function exists in the `lib` folder within `node_modules`. Could you please tell me what might be causing this?

**Comment by vinodiOS** [comment]
@like202012 @dale-wahl url has been changed to https://amp-api-edge.apps.apple.com/v1/catalog

**Comment by adtimizer** [comment]
@vinodiOS did you manage to fix privacy function?

**Comment by vinodiOS** [comment]
@adtimizer yes. Check https://github.com/facundoolano/app-store-scraper/pull/225

**Comment by qomhmd** [comment]
Broken again, can be fixed by https://github.com/facundoolano/app-store-scraper/commit/f8dcf604eab6a69fc3edfa203ae50c292f274066
